name: pyapp test
# Adopted from https://github.com/mitmproxy/pdoc/blob/25f325d06aaacba9711f957f48e770029f608f6a/.github/workflows/docs.yml

on:
  push:
    branches:
      - main
      - oop-oob

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"   

      - name: Install hatch
        run: python -m pip install hatch

      - name: Create environment
        run: hatch env create

      - name: Install flake8
        run: |
            python -m pip install --upgrade pip
            pip install pytest

      - name: Install opencv2
        run: |
            sudo apt update && sudo apt install libopencv-dev     

      - name: Build OpenCFU
        run: |
            git clone https://github.com/msudesigncpr/OpenCFU/tree/master
            cd OpenCFU
            autoreconf -i
            automake --add-missing


      - name:  Test with pytest
        run: pytest

    